import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("data source panel supports experimental provider status", () => {
  const typesSource = readFileSync(new URL("./types.ts", import.meta.url), "utf8");
  const apiSource = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
  const panelSource = readFileSync(new URL("../components/DataSourceStatusPanel.tsx", import.meta.url), "utf8");

  assert.match(typesSource, /"experimental"/);
  assert.match(typesSource, /DataSourceOption/);
  assert.match(typesSource, /DataSourceOptionsResponse/);
  assert.match(typesSource, /DataSourceOptionsUpdate/);
  assert.match(typesSource, /AStockVendorStatus/);
  assert.match(apiSource, /getDataSourceOptions/);
  assert.match(apiSource, /updateDataSourceOptions/);
  assert.match(apiSource, /getAStockVendorStatus/);
  assert.match(apiSource, /checkAStockVendor/);
  assert.match(apiSource, /updateAStockVendor/);
  assert.match(apiSource, /updateAStockVendorAutoCheck/);
  assert.match(panelSource, /experimental:/);
  assert.match(panelSource, /fallback_enabled/);
  assert.match(panelSource, /review_sources/);
  assert.match(panelSource, /a-stock-data 接口版本/);
  assert.match(panelSource, /检查更新/);
  assert.match(panelSource, /更新参考接口/);
  assert.match(panelSource, /每天自动检查/);
  assert.match(panelSource, /onSave/);
  assert.match(panelSource, /role="switch"/);
  assert.match(panelSource, /aria-checked=\{draft\.fallback_enabled\}/);
  assert.match(panelSource, /保存数据源选项中/);
  assert.match(panelSource, /border-l-4/);
  assert.match(panelSource, /key=\{`\$\{item\.name\}-\$\{item\.role\}`\}/);
  assert.doesNotMatch(panelSource, /key=\{item\.name\}/);
  assert.doesNotMatch(panelSource, /a_stock_dragon_tiger/);
  assert.match(panelSource, /category\.options\.map/);
  assert.match(panelSource, /option\.key/);
  assert.match(panelSource, /option\.label/);
  assert.match(panelSource, /option\.role/);
});
